// Mock data for the Longitudinal Skilling Outcomes and Impact Measurement Platform (SIH)
// Complete workflow: TRAINING -> EMPLOYMENT OUTCOME -> EMPLOYER VERIFICATION -> 30/90/180-DAY FOLLOW-UP -> LONGITUDINAL OUTCOMES -> ADMIN ANALYTICS

export const mockCompanies = [
  {
    companyId: "COMP-001",
    name: "ABC Technologies",
    cin: "U72200KA2018PTC112345",
    sector: "Information Technology & Software",
    location: "Bengaluru / Kolkata",
    nodalOfficer: "Ramesh Sen (HR Manager)",
    email: "hr@abctechnologies.com",
    phone: "+91 80 4455 6677",
  },
  {
    companyId: "COMP-002",
    name: "Asha Industries",
    cin: "U29100WB2015PTC098765",
    sector: "Electrical Equipment & Capital Goods",
    location: "Kolkata, West Bengal",
    nodalOfficer: "Sunita Bannerjee (Talent Acquisition)",
    email: "hr@ashaindustries.in",
    phone: "+91 33 2288 9900",
  },
  {
    companyId: "COMP-003",
    name: "Tata Consultancy Services",
    cin: "L22210MH1995PLC084781",
    sector: "IT Services & Engineering Operations",
    location: "Pune, Maharashtra",
    nodalOfficer: "Amit Kulkarni (Apprenticeship Lead)",
    email: "tcs.apprenticeship@tcs.com",
    phone: "+91 20 6677 8899",
  },
  {
    companyId: "COMP-004",
    name: "L&T Construction",
    cin: "L99999MH1946PLC004768",
    sector: "Infrastructure & Logistics",
    location: "Lucknow, Uttar Pradesh",
    nodalOfficer: "Vikas Shukla (Regional HR)",
    email: "hr.north@lntconstruction.com",
    phone: "+91 522 2334455",
  },
  {
    companyId: "COMP-005",
    name: "Rajasthan Textiles",
    cin: "U17119RJ2012PTC040112",
    sector: "Apparel & Garment Manufacturing",
    location: "Jaipur, Rajasthan",
    nodalOfficer: "Mahesh Choudhary (Plant HR)",
    email: "recruitment@rajasthantextiles.com",
    phone: "+91 141 2788990",
  },
  {
    companyId: "COMP-006",
    name: "Coastal Foods & Cold Chain",
    cin: "U15122KL2016PTC042211",
    sector: "Food Processing & Cold Chain",
    location: "Ernakulam, Kerala",
    nodalOfficer: "Deepa Menon (Operations HR)",
    email: "hr@coastalfoods.co.in",
    phone: "+91 484 2556677",
  },
  {
    companyId: "COMP-007",
    name: "XYZ Ltd",
    cin: "U74999DL2021PTC384455",
    sector: "Consulting & Business Support",
    location: "New Delhi",
    nodalOfficer: "Pooja Roy (HR Generalist)",
    email: "contact@xyzltd.example.com",
    phone: "+91 11 4122 3344",
  },
];

export const mockCourses = [
  "Full Stack Development",
  "Industrial Electrician & PLC",
  "Industrial Quality Assurance",
  "Solar PV Installation & Maintenance",
  "Food Processing & Safety Compliance",
  "Logistics & Warehouse Management",
  "CNC Machine Operation",
  "Healthcare Assistant & Patient Care",
];

export const mockProviders = [
  "ABC Training Centre",
  "West Bengal Skills Centre",
  "Apex Technical Institute",
  "National Skill Training Centre",
  "South India Food Tech Academy",
  "Uttar Pradesh Skill Mission Centre",
  "Precision Engineering Skills Centre",
];

export const mockDistricts = [
  { district: "Kolkata", state: "West Bengal" },
  { district: "Jaipur", state: "Rajasthan" },
  { district: "Lucknow", state: "Uttar Pradesh" },
  { district: "Pune", state: "Maharashtra" },
  { district: "Ernakulam", state: "Kerala" },
  { district: "Hyderabad", state: "Telangana" },
];

export const mockTrainees = [
  {
    userId: "USR-1001",
    traineeId: "TRN-1001",
    name: "Rahul Kumar",
    email: "rahul@example.com",
    phone: "9876543210",
    district: "Kolkata",
    state: "West Bengal",
    consent: true,
    course: "Full Stack Development",
    provider: "ABC Training Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-FSD-2026-8812",
    completedOn: "2026-07-20",
    programme: "PMKVY Digital Skills",
    employmentStatus: "Employed",
    employer: "ABC Technologies",
    jobRole: "Junior Developer",
    salary: 18000,
    currentSalary: 20000,
    joinedOn: "2026-08-10",
    location: "Kolkata, West Bengal",
    skillsUsed: "React, JavaScript, Node.js, REST APIs",
    verificationStatus: "Pending",
    submittedOn: "2026-08-11",
    verificationNotes: "Awaiting review by ABC Technologies HR officer.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 95,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-09-10",
        completedOn: "2026-09-08",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 18000,
        jobRelevant: "Yes",
        feedback: "Successfully adapted to sprint tasks, mentored by senior developer.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-11-10",
        completedOn: "2026-11-05",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 20000,
        jobRelevant: "Yes",
        feedback: "Confirmed probation with performance-based increment of ₹2,000.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-02-10",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1002",
    traineeId: "TRN-1002",
    name: "Anjali Sharma",
    email: "anjali@example.com",
    phone: "9812345678",
    district: "Jaipur",
    state: "Rajasthan",
    consent: true,
    course: "Industrial Quality Assurance",
    provider: "Apex Technical Institute",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-IQA-2026-4401",
    completedOn: "2026-05-20",
    programme: "DDU-GKY Technical",
    employmentStatus: "Employed",
    employer: "Rajasthan Textiles",
    jobRole: "Quality Inspector",
    salary: 24000,
    currentSalary: 27000,
    joinedOn: "2026-06-01",
    location: "Jaipur, Rajasthan",
    skillsUsed: "ISO 9001 Inspection, Fabric Testing, Statistical Process Control",
    verificationStatus: "Verified",
    submittedOn: "2026-06-02",
    verificationNotes: "Candidate verified on active payroll in Quality Assurance department.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 100,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-07-01",
        completedOn: "2026-06-30",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 24000,
        jobRelevant: "Yes",
        feedback: "Handling yarn defect tracking and batch certifications.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-09-01",
        completedOn: "2026-08-30",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 25500,
        jobRelevant: "Yes",
        feedback: "Promoted to shift quality lead with ₹1,500 increment.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2026-12-01",
        completedOn: "2026-11-28",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 27000,
        jobRelevant: "Yes",
        feedback: "Six months completed. Certified as lead auditor.",
      },
    ],
  },
  {
    userId: "USR-1003",
    traineeId: "TRN-1003",
    name: "Mohammed Irfan",
    email: "irfan@example.com",
    phone: "9900112233",
    district: "Hyderabad",
    state: "Telangana",
    consent: true,
    course: "Solar PV Installation & Maintenance",
    provider: "National Skill Training Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-SOL-2026-3011",
    completedOn: "2026-06-15",
    programme: "PMKVY Green Jobs",
    employmentStatus: "Unemployed",
    employer: "None",
    jobRole: "None",
    salary: 0,
    currentSalary: 0,
    joinedOn: null,
    location: "Hyderabad, Telangana",
    skillsUsed: "Rooftop PV Mounting, Inverter Diagnostics",
    verificationStatus: "Not applicable",
    submittedOn: "2026-07-01",
    verificationNotes: "Self-declared unemployment due to local market constraints.",
    rejectionReason: "",
    unemploymentReason:
      "Lack of local job opportunities in renewable sector; preparing for state electricity board exam",
    skillGap: "Commercial 3-phase grid integration & interview readiness",
    jobRelevance: "Low",
    flagged: true,
    profileCompletion: 85,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-07-20",
        completedOn: "2026-07-18",
        status: "Completed",
        stillWithEmployer: false,
        currentStatus: "Unemployed",
        salary: 0,
        jobRelevant: "No",
        feedback: "Actively applying to EPC contractors in Rangareddy district.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-09-20",
        completedOn: null,
        status: "Overdue",
        stillWithEmployer: false,
        currentStatus: "Unemployed",
        salary: 0,
        jobRelevant: "No",
        feedback: "Mobilization officer contact requested for interview scheduling.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2026-12-20",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1004",
    traineeId: "TRN-1004",
    name: "Priya Nair",
    email: "priya@example.com",
    phone: "9745001122",
    district: "Ernakulam",
    state: "Kerala",
    consent: true,
    course: "Food Processing & Safety Compliance",
    provider: "South India Food Tech Academy",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-FSS-2026-1920",
    completedOn: "2026-06-25",
    programme: "PMKVY Food Sector",
    employmentStatus: "Employed",
    employer: "Coastal Foods & Cold Chain",
    jobRole: "Packaging & Quality Associate",
    salary: 21000,
    currentSalary: 16000,
    joinedOn: "2026-07-01",
    location: "Ernakulam, Kerala",
    skillsUsed: "HACCP, Cold Storage Temperature Logging",
    verificationStatus: "Rejected",
    submittedOn: "2026-07-03",
    verificationNotes: "Discrepancy identified during HR verification audit.",
    rejectionReason:
      "Candidate joined on 01/07/2026 but resigned after 4 days during induction training period.",
    jobRelevance: "Partially",
    attritionReason:
      "Adverse physical working conditions (continuous sub-zero temperature exposure)",
    skillGap: "Workplace ergonomic resilience & industrial safety adaptation",
    flagged: true,
    profileCompletion: 90,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-08-05",
        completedOn: "2026-08-04",
        status: "Completed",
        stillWithEmployer: false,
        currentStatus: "Unemployed",
        salary: 0,
        jobRelevant: "No",
        feedback:
          "Left Coastal Foods due to health reasons; seeking retail food safety auditing roles.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-10-05",
        completedOn: "2026-10-02",
        status: "Completed",
        stillWithEmployer: false,
        currentStatus: "Employed",
        salary: 16000,
        jobRelevant: "Partially",
        feedback: "Joined local supermarket chain as inventory quality assistant.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-01-05",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1005",
    traineeId: "TRN-1005",
    name: "Sandeep Yadav",
    email: "sandeep@example.com",
    phone: "9001122334",
    district: "Lucknow",
    state: "Uttar Pradesh",
    consent: true,
    course: "Logistics & Warehouse Management",
    provider: "Uttar Pradesh Skill Mission Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-LGT-2026-9043",
    completedOn: "2026-03-01",
    programme: "DDU-GKY Logistics",
    employmentStatus: "Employed",
    employer: "L&T Construction",
    jobRole: "Inventory & Materials Coordinator",
    salary: 19500,
    currentSalary: 23500,
    joinedOn: "2026-03-15",
    location: "Lucknow, Uttar Pradesh",
    skillsUsed: "SAP ERP, Inventory Auditing, Material Dispatch",
    verificationStatus: "Verified",
    submittedOn: "2026-03-16",
    verificationNotes: "Verified by Regional Logistics Head. Active on site deployment.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 100,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-04-15",
        completedOn: "2026-04-14",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 19500,
        jobRelevant: "Yes",
        feedback: "Managing cement and steel inventory registers.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-06-15",
        completedOn: "2026-06-12",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 21000,
        jobRelevant: "Yes",
        feedback: "Received warehouse safety recognition bonus.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2026-09-15",
        completedOn: "2026-09-02",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 23500,
        jobRelevant: "Yes",
        feedback: "Promoted to Section Store In-Charge. 180-day retention verified.",
      },
    ],
  },
  {
    userId: "USR-1006",
    traineeId: "TRN-1006",
    name: "Meera Das",
    email: "meera@example.com",
    phone: "9123456789",
    district: "Kolkata",
    state: "West Bengal",
    consent: true,
    course: "Industrial Electrician & PLC",
    provider: "West Bengal Skills Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-ELC-2026-2180",
    completedOn: "2026-07-15",
    programme: "PMKVY Industrial",
    employmentStatus: "Employed",
    employer: "Asha Industries",
    jobRole: "Electrical Technician",
    salary: 22000,
    currentSalary: 22000,
    joinedOn: "2026-08-01",
    location: "Kolkata, West Bengal",
    skillsUsed: "Wiring, Single-phase/3-phase motors, PLC panel wiring",
    verificationStatus: "Pending",
    submittedOn: "2026-08-03",
    verificationNotes: "Pending document verification with Asha Industries payroll.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 95,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-09-01",
        completedOn: "2026-08-30",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 22000,
        jobRelevant: "Yes",
        feedback: "Assigned to motor maintenance floor in second shift.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-11-01",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-02-01",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1007",
    traineeId: "TRN-1007",
    name: "Vikram Singh",
    email: "vikram@example.com",
    phone: "9870011223",
    district: "Pune",
    state: "Maharashtra",
    consent: true,
    course: "CNC Machine Operation",
    provider: "Precision Engineering Skills Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-CNC-2026-5561",
    completedOn: "2026-06-30",
    programme: "National Apprenticeship Promotion Scheme (NAPS)",
    employmentStatus: "Apprentice",
    employer: "Tata Consultancy Services",
    jobRole: "Graduate Apprentice Trainee (Tooling)",
    salary: 15000,
    currentSalary: 21000,
    joinedOn: "2026-07-15",
    location: "Pune, Maharashtra",
    skillsUsed: "G-Code Programming, Milling, Lathe Operations",
    verificationStatus: "Verified",
    submittedOn: "2026-07-16",
    verificationNotes: "Approved under NAPS apprentice contract #TCS-PUN-8821.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 100,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-08-15",
        completedOn: "2026-08-14",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Apprentice",
        salary: 15000,
        jobRelevant: "Yes",
        feedback: "Apprenticeship orientation completed; operating 3-axis CNC.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-10-15",
        completedOn: "2026-10-10",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 21000,
        jobRelevant: "Yes",
        feedback: "Converted to full-time Associate Tooling Technician.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-01-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1008",
    traineeId: "TRN-1008",
    name: "Pooja Choudhary",
    email: "pooja@example.com",
    phone: "9788112244",
    district: "Jaipur",
    state: "Rajasthan",
    consent: true,
    course: "Healthcare Assistant & Patient Care",
    provider: "Apex Technical Institute",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-HCA-2026-7201",
    completedOn: "2026-05-30",
    programme: "PMKVY Healthcare",
    employmentStatus: "Self-employed",
    employer: "Self-employed (Home Patient Care)",
    jobRole: "Independent Caregiver",
    salary: 17500,
    currentSalary: 19500,
    joinedOn: "2026-06-20",
    location: "Jaipur, Rajasthan",
    skillsUsed: "Vital Signs, Elder Care, Mobility Support, First Aid",
    verificationStatus: "Verified",
    submittedOn: "2026-06-22",
    verificationNotes:
      "Self-employment verified via client service log and bank deposit declaration.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 100,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-07-20",
        completedOn: "2026-07-18",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Self-employed",
        salary: 17500,
        jobRelevant: "Yes",
        feedback: "Servicing 2 regular residential elderly patients.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-09-20",
        completedOn: "2026-09-05",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Self-employed",
        salary: 19500,
        jobRelevant: "Yes",
        feedback: "Expanded services to weekend post-operative assistance.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2026-12-20",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1009",
    traineeId: "TRN-1009",
    name: "Tanmay Sen",
    email: "tanmay@example.com",
    phone: "9831002233",
    district: "Kolkata",
    state: "West Bengal",
    consent: true,
    course: "Full Stack Development",
    provider: "ABC Training Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-FSD-2026-8845",
    completedOn: "2026-07-20",
    programme: "PMKVY Digital Skills",
    employmentStatus: "Employed",
    employer: "ABC Technologies",
    jobRole: "QA Automation Engineer",
    salary: 19000,
    currentSalary: 19000,
    joinedOn: "2026-08-15",
    location: "Kolkata, West Bengal",
    skillsUsed: "Jest, Cypress, React Testing, GitHub CI/CD",
    verificationStatus: "Pending",
    submittedOn: "2026-08-16",
    verificationNotes: "Pending confirmation from ABC Technologies QA Team Lead.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 95,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-09-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 19000,
        jobRelevant: "Yes",
        feedback: null,
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-11-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-02-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1010",
    traineeId: "TRN-1010",
    name: "Kavita Rawat",
    email: "kavita@example.com",
    phone: "9450112233",
    district: "Lucknow",
    state: "Uttar Pradesh",
    consent: true,
    course: "Industrial Electrician & PLC",
    provider: "Uttar Pradesh Skill Mission Centre",
    trainingStatus: "Completed",
    certificationStatus: "Not Certified",
    certificateId: null,
    completedOn: "2026-07-28",
    programme: "DDU-GKY Technical",
    employmentStatus: "Unemployed",
    employer: "None",
    jobRole: "None",
    salary: 0,
    currentSalary: 0,
    joinedOn: null,
    location: "Lucknow, Uttar Pradesh",
    skillsUsed: "",
    verificationStatus: "Not applicable",
    submittedOn: "2026-08-01",
    verificationNotes: "Awaiting supplementary practical trade exam in October 2026.",
    rejectionReason: "",
    unemploymentReason:
      "Failed practical assessment component; awaiting re-assessment to obtain certification",
    skillGap: "High-voltage switchgear safety & wiring schematics",
    jobRelevance: "Low",
    flagged: true,
    profileCompletion: 80,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-09-01",
        completedOn: "2026-08-28",
        status: "Completed",
        stillWithEmployer: false,
        currentStatus: "Unemployed",
        salary: 0,
        jobRelevant: "No",
        feedback: "Enrolled in remedial weekend workshop at training centre.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-11-01",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-02-01",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1011",
    traineeId: "TRN-1011",
    name: "Rohit Verma",
    email: "rohit@example.com",
    phone: "9829001122",
    district: "Jaipur",
    state: "Rajasthan",
    consent: true,
    course: "Logistics & Warehouse Management",
    provider: "Apex Technical Institute",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-LGT-2026-9110",
    completedOn: "2026-06-28",
    programme: "DDU-GKY Logistics",
    employmentStatus: "Employed",
    employer: "Rajasthan Textiles",
    jobRole: "Warehouse Dispatch Clerk",
    salary: 16500,
    currentSalary: 0,
    joinedOn: "2026-07-10",
    location: "Jaipur, Rajasthan",
    skillsUsed: "Inventory Dispatch, Barcode Scanning",
    verificationStatus: "Rejected",
    submittedOn: "2026-07-12",
    verificationNotes: "Claim rejected by employer during payroll audit.",
    rejectionReason:
      "Salary reported as ₹16,500 but offer was ₹12,500 part-time; offer was rejected by candidate before formal joining.",
    jobRelevance: "Partially",
    attritionReason: "Compensation mismatch between reported claim and formal offer letter",
    skillGap: "Wage negotiation & formal employment terms awareness",
    flagged: true,
    profileCompletion: 90,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-08-15",
        completedOn: "2026-08-10",
        status: "Completed",
        stillWithEmployer: false,
        currentStatus: "Unemployed",
        salary: 0,
        jobRelevant: "No",
        feedback: "Looking for full-time warehouse jobs offering minimum ₹15,000 base.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-10-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2027-01-15",
        completedOn: null,
        status: "Pending",
        stillWithEmployer: null,
        currentStatus: null,
        salary: null,
        jobRelevant: null,
        feedback: null,
      },
    ],
  },
  {
    userId: "USR-1012",
    traineeId: "TRN-1012",
    name: "Farhan Akhtar",
    email: "farhan@example.com",
    phone: "9830554433",
    district: "Kolkata",
    state: "West Bengal",
    consent: true,
    course: "CNC Machine Operation",
    provider: "West Bengal Skills Centre",
    trainingStatus: "Completed",
    certificationStatus: "Certified",
    certificateId: "NSDC-CNC-2026-1189",
    completedOn: "2026-04-20",
    programme: "PMKVY Industrial",
    employmentStatus: "Employed",
    employer: "Asha Industries",
    jobRole: "CNC Machine Operator",
    salary: 20500,
    currentSalary: 24000,
    joinedOn: "2026-05-10",
    location: "Kolkata, West Bengal",
    skillsUsed: "CNC Tooling, Fanuc Controller, Precision Milling",
    verificationStatus: "Verified",
    submittedOn: "2026-05-12",
    verificationNotes: "Verified by Asha Industries Machine Shop Foreman.",
    rejectionReason: "",
    jobRelevance: "High",
    flagged: false,
    profileCompletion: 100,
    followUps: [
      {
        milestone: "30-day",
        title: "30-Day Follow-Up",
        dueOn: "2026-06-10",
        completedOn: "2026-06-08",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 20500,
        jobRelevant: "Yes",
        feedback: "Operating vertical machining centre without supervision.",
      },
      {
        milestone: "90-day",
        title: "90-Day Follow-Up",
        dueOn: "2026-08-10",
        completedOn: "2026-08-05",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 22000,
        jobRelevant: "Yes",
        feedback: "Received productivity incentive of ₹1,500/month.",
      },
      {
        milestone: "180-day",
        title: "180-Day Follow-Up",
        dueOn: "2026-11-10",
        completedOn: "2026-11-02",
        status: "Completed",
        stillWithEmployer: true,
        currentStatus: "Employed",
        salary: 24000,
        jobRelevant: "Yes",
        feedback: "180-day retention verified. Certified for dual-spindle machining.",
      },
    ],
  },
];

// Initial mock current user profiles for demonstration switchers
export const defaultTrainee = mockTrainees[0]; // Rahul Kumar

export const mockEmployerAccounts = [
  {
    userId: "USR-EMP-001",
    name: "ABC Technologies HR",
    email: "hr@abctechnologies.com",
    role: "employer",
    companyName: "ABC Technologies",
    companyId: "COMP-001",
  },
  {
    userId: "USR-EMP-002",
    name: "Asha Industries HR",
    email: "hr@ashaindustries.in",
    role: "employer",
    companyName: "Asha Industries",
    companyId: "COMP-002",
  },
  {
    userId: "USR-EMP-003",
    name: "Rajasthan Textiles HR",
    email: "hr@rajasthantextiles.com",
    role: "employer",
    companyName: "Rajasthan Textiles",
    companyId: "COMP-005",
  },
  {
    userId: "USR-EMP-004",
    name: "XYZ Ltd HR",
    email: "hr@xyzltd.com",
    role: "employer",
    companyName: "XYZ Ltd",
    companyId: "COMP-007",
  },
];

export const mockAdminAccounts = [
  {
    userId: "USR-ADM-001",
    name: "Dr. K. Swaminathan",
    email: "admin@msde.gov.in",
    role: "admin",
    scope: "Super Admin",
    scopeTarget: "All India",
    designation: "National Director - Longitudinal Outcomes",
  },
  {
    userId: "USR-ADM-002",
    name: "Debasish Mukherjee",
    email: "wb.admin@skills.gov.in",
    role: "admin",
    scope: "State Admin",
    scopeTarget: "West Bengal",
    designation: "State Mission Director (West Bengal)",
  },
  {
    userId: "USR-ADM-003",
    name: "Sunil Rathore",
    email: "jaipur.admin@skills.gov.in",
    role: "admin",
    scope: "District Admin",
    scopeTarget: "Jaipur",
    designation: "District Skill Officer (Jaipur)",
  },
  {
    userId: "USR-ADM-004",
    name: "Priyanka Joshi",
    email: "pmkvy.lead@nsdc.org",
    role: "admin",
    scope: "Programme Admin",
    scopeTarget: "PMKVY Digital Skills",
    designation: "PMKVY Digital Portfolio Lead",
  },
];
